// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenSeaClient.DemoConsole;

#nullable disable

namespace OpenSeaClient.DemoConsole.Migrations
{
    [DbContext(typeof(AssetsDbContext))]
    [Migration("20220124165656_AddIsProcessedToAssets")]
    partial class AddIsProcessedToAssets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("OpenSeaClient.DemoConsole.AssetDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Accumulated")
                        .HasColumnType("REAL");

                    b.Property<string>("CollectionSlug")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsOnSale")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("TokenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TraitType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
